logs:
  base:
    dir: logs

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048
  servlet:
    context-path: /@project.build.finalName@
